name: Android Publish

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: macOS-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          GOOGLE_JSON_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_JSON_SECRET_PASSPHRASE }}
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
#       - name: Run unit tests
#         run: ./gradlew testDebugUnitTest

#       - name: Run instrumentation tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 30
#           target: google_apis
#           script: ./gradlew connectedCheck --stacktrace

      - name: Build release aab
        run: ./gradlew bundleRelease

      - name: Sign aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: com.github.anastr.myscore
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          
